package in_error

import "errors"

var ErrAlreadyExists = errors.New("record already exists")
